//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: message.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Message_MessageClient, then call methods of this protocol to make API calls.
internal protocol Message_MessageClientProtocol: GRPCClient {
  func get_messages_in_group(
    _ request: Message_GetMessagesInGroupRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_GetMessagesInGroupRequest, Message_GetMessagesInGroupResponse>

  func subscribe(
    _ request: Message_SubscribeAndListenRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_SubscribeAndListenRequest, Message_BaseResponse>

  func listen(
    _ request: Message_SubscribeAndListenRequest,
    callOptions: CallOptions?,
    handler: @escaping (Message_MessageObjectResponse) -> Void
  ) -> ServerStreamingCall<Message_SubscribeAndListenRequest, Message_MessageObjectResponse>

  func publish(
    _ request: Message_PublishRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Message_PublishRequest, Message_MessageObjectResponse>

}

extension Message_MessageClientProtocol {

  /// Unary call to get_messages_in_group
  ///
  /// - Parameters:
  ///   - request: Request to send to get_messages_in_group.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get_messages_in_group(
    _ request: Message_GetMessagesInGroupRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_GetMessagesInGroupRequest, Message_GetMessagesInGroupResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/get_messages_in_group",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  ///action
  ///
  /// - Parameters:
  ///   - request: Request to send to Subscribe.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func subscribe(
    _ request: Message_SubscribeAndListenRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_SubscribeAndListenRequest, Message_BaseResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/Subscribe",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Server streaming call to Listen
  ///
  /// - Parameters:
  ///   - request: Request to send to Listen.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func listen(
    _ request: Message_SubscribeAndListenRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Message_MessageObjectResponse) -> Void
  ) -> ServerStreamingCall<Message_SubscribeAndListenRequest, Message_MessageObjectResponse> {
    return self.makeServerStreamingCall(
      path: "/message.Message/Listen",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      handler: handler
    )
  }

  /// Unary call to Publish
  ///
  /// - Parameters:
  ///   - request: Request to send to Publish.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func publish(
    _ request: Message_PublishRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Message_PublishRequest, Message_MessageObjectResponse> {
    return self.makeUnaryCall(
      path: "/message.Message/Publish",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class Message_MessageClient: Message_MessageClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the message.Message service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Message_MessageProvider: CallHandlerProvider {
  func get_messages_in_group(request: Message_GetMessagesInGroupRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_GetMessagesInGroupResponse>
  ///action
  func subscribe(request: Message_SubscribeAndListenRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_BaseResponse>
  func listen(request: Message_SubscribeAndListenRequest, context: StreamingResponseCallContext<Message_MessageObjectResponse>) -> EventLoopFuture<GRPCStatus>
  func publish(request: Message_PublishRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Message_MessageObjectResponse>
}

extension Message_MessageProvider {
  internal var serviceName: Substring { return "message.Message" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "get_messages_in_group":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.get_messages_in_group(request: request, context: context)
        }
      }

    case "Subscribe":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.subscribe(request: request, context: context)
        }
      }

    case "Listen":
      return CallHandlerFactory.makeServerStreaming(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listen(request: request, context: context)
        }
      }

    case "Publish":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.publish(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

