//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: notify.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate Notification_NotifyClient, then call methods of this protocol to make API calls.
internal protocol Notification_NotifyClientProtocol: GRPCClient {
  func read_notify(
    _ request: Notification_ReadNotifyRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Notification_ReadNotifyRequest, Notification_BaseResponse>

  func get_unread_notifies(
    _ request: Notification_Empty,
    callOptions: CallOptions?
  ) -> UnaryCall<Notification_Empty, Notification_GetNotifiesResponse>

  func subscribe(
    _ request: Notification_SubscribeAndListenRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<Notification_SubscribeAndListenRequest, Notification_BaseResponse>

  func listen(
    _ request: Notification_SubscribeAndListenRequest,
    callOptions: CallOptions?,
    handler: @escaping (Notification_NotifyObjectResponse) -> Void
  ) -> ServerStreamingCall<Notification_SubscribeAndListenRequest, Notification_NotifyObjectResponse>

}

extension Notification_NotifyClientProtocol {

  /// Unary call to read_notify
  ///
  /// - Parameters:
  ///   - request: Request to send to read_notify.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func read_notify(
    _ request: Notification_ReadNotifyRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Notification_ReadNotifyRequest, Notification_BaseResponse> {
    return self.makeUnaryCall(
      path: "/notification.Notify/read_notify",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to get_unread_notifies
  ///
  /// - Parameters:
  ///   - request: Request to send to get_unread_notifies.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func get_unread_notifies(
    _ request: Notification_Empty,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Notification_Empty, Notification_GetNotifiesResponse> {
    return self.makeUnaryCall(
      path: "/notification.Notify/get_unread_notifies",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Unary call to subscribe
  ///
  /// - Parameters:
  ///   - request: Request to send to subscribe.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func subscribe(
    _ request: Notification_SubscribeAndListenRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<Notification_SubscribeAndListenRequest, Notification_BaseResponse> {
    return self.makeUnaryCall(
      path: "/notification.Notify/subscribe",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }

  /// Server streaming call to listen
  ///
  /// - Parameters:
  ///   - request: Request to send to listen.
  ///   - callOptions: Call options.
  ///   - handler: A closure called when each response is received from the server.
  /// - Returns: A `ServerStreamingCall` with futures for the metadata and status.
  internal func listen(
    _ request: Notification_SubscribeAndListenRequest,
    callOptions: CallOptions? = nil,
    handler: @escaping (Notification_NotifyObjectResponse) -> Void
  ) -> ServerStreamingCall<Notification_SubscribeAndListenRequest, Notification_NotifyObjectResponse> {
    return self.makeServerStreamingCall(
      path: "/notification.Notify/listen",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      handler: handler
    )
  }
}

internal final class Notification_NotifyClient: Notification_NotifyClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the notification.Notify service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol Notification_NotifyProvider: CallHandlerProvider {
  func read_notify(request: Notification_ReadNotifyRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Notification_BaseResponse>
  func get_unread_notifies(request: Notification_Empty, context: StatusOnlyCallContext) -> EventLoopFuture<Notification_GetNotifiesResponse>
  func subscribe(request: Notification_SubscribeAndListenRequest, context: StatusOnlyCallContext) -> EventLoopFuture<Notification_BaseResponse>
  func listen(request: Notification_SubscribeAndListenRequest, context: StreamingResponseCallContext<Notification_NotifyObjectResponse>) -> EventLoopFuture<GRPCStatus>
}

extension Notification_NotifyProvider {
  internal var serviceName: Substring { return "notification.Notify" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "read_notify":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.read_notify(request: request, context: context)
        }
      }

    case "get_unread_notifies":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.get_unread_notifies(request: request, context: context)
        }
      }

    case "subscribe":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.subscribe(request: request, context: context)
        }
      }

    case "listen":
      return CallHandlerFactory.makeServerStreaming(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.listen(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

