//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: video_call.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate VideoCall_VideoCallClient, then call methods of this protocol to make API calls.
internal protocol VideoCall_VideoCallClientProtocol: GRPCClient {
  func video_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse>

}

extension VideoCall_VideoCallClientProtocol {

  /// Unary call to video_call
  ///
  /// - Parameters:
  ///   - request: Request to send to video_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func video_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/video_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions
    )
  }
}

internal final class VideoCall_VideoCallClient: VideoCall_VideoCallClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions

  /// Creates a client for the video_call.VideoCall service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  internal init(channel: GRPCChannel, defaultCallOptions: CallOptions = CallOptions()) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol VideoCall_VideoCallProvider: CallHandlerProvider {
  func video_call(request: VideoCall_VideoCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_BaseResponse>
}

extension VideoCall_VideoCallProvider {
  internal var serviceName: Substring { return "video_call.VideoCall" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handleMethod(_ methodName: Substring, callHandlerContext: CallHandlerContext) -> GRPCCallHandler? {
    switch methodName {
    case "video_call":
      return CallHandlerFactory.makeUnary(callHandlerContext: callHandlerContext) { context in
        return { request in
          self.video_call(request: request, context: context)
        }
      }

    default: return nil
    }
  }
}

