//
// DO NOT EDIT.
//
// Generated by the protocol buffer compiler.
// Source: video_call.proto
//

//
// Copyright 2018, gRPC Authors All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
import GRPC
import NIO
import SwiftProtobuf


/// Usage: instantiate `VideoCall_VideoCallClient`, then call methods of this protocol to make API calls.
internal protocol VideoCall_VideoCallClientProtocol: GRPCClient {
  var serviceName: String { get }
  var interceptors: VideoCall_VideoCallClientInterceptorFactoryProtocol? { get }

  func video_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_ServerResponse>

  func cancel_request_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse>

  func miss_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse>

  func decline_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse>

  func end_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse>

  func update_call(
    _ request: VideoCall_UpdateCallRequest,
    callOptions: CallOptions?
  ) -> UnaryCall<VideoCall_UpdateCallRequest, VideoCall_BaseResponse>
}

extension VideoCall_VideoCallClientProtocol {
  internal var serviceName: String {
    return "video_call.VideoCall"
  }

  /// Unary call to video_call
  ///
  /// - Parameters:
  ///   - request: Request to send to video_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func video_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_ServerResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/video_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makevideo_callInterceptors() ?? []
    )
  }

  /// Unary call to cancel_request_call
  ///
  /// - Parameters:
  ///   - request: Request to send to cancel_request_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func cancel_request_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/cancel_request_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makecancel_request_callInterceptors() ?? []
    )
  }

  /// Unary call to miss_call
  ///
  /// - Parameters:
  ///   - request: Request to send to miss_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func miss_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/miss_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makemiss_callInterceptors() ?? []
    )
  }

  /// Unary call to decline_call
  ///
  /// - Parameters:
  ///   - request: Request to send to decline_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func decline_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/decline_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makedecline_callInterceptors() ?? []
    )
  }

  /// Unary call to end_call
  ///
  /// - Parameters:
  ///   - request: Request to send to end_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func end_call(
    _ request: VideoCall_VideoCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_VideoCallRequest, VideoCall_BaseResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/end_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeend_callInterceptors() ?? []
    )
  }

  /// Unary call to update_call
  ///
  /// - Parameters:
  ///   - request: Request to send to update_call.
  ///   - callOptions: Call options.
  /// - Returns: A `UnaryCall` with futures for the metadata, status and response.
  internal func update_call(
    _ request: VideoCall_UpdateCallRequest,
    callOptions: CallOptions? = nil
  ) -> UnaryCall<VideoCall_UpdateCallRequest, VideoCall_BaseResponse> {
    return self.makeUnaryCall(
      path: "/video_call.VideoCall/update_call",
      request: request,
      callOptions: callOptions ?? self.defaultCallOptions,
      interceptors: self.interceptors?.makeupdate_callInterceptors() ?? []
    )
  }
}

internal protocol VideoCall_VideoCallClientInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when invoking 'video_call'.
  func makevideo_callInterceptors() -> [ClientInterceptor<VideoCall_VideoCallRequest, VideoCall_ServerResponse>]

  /// - Returns: Interceptors to use when invoking 'cancel_request_call'.
  func makecancel_request_callInterceptors() -> [ClientInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'miss_call'.
  func makemiss_callInterceptors() -> [ClientInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'decline_call'.
  func makedecline_callInterceptors() -> [ClientInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'end_call'.
  func makeend_callInterceptors() -> [ClientInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when invoking 'update_call'.
  func makeupdate_callInterceptors() -> [ClientInterceptor<VideoCall_UpdateCallRequest, VideoCall_BaseResponse>]
}

internal final class VideoCall_VideoCallClient: VideoCall_VideoCallClientProtocol {
  internal let channel: GRPCChannel
  internal var defaultCallOptions: CallOptions
  internal var interceptors: VideoCall_VideoCallClientInterceptorFactoryProtocol?

  /// Creates a client for the video_call.VideoCall service.
  ///
  /// - Parameters:
  ///   - channel: `GRPCChannel` to the service host.
  ///   - defaultCallOptions: Options to use for each service call if the user doesn't provide them.
  ///   - interceptors: A factory providing interceptors for each RPC.
  internal init(
    channel: GRPCChannel,
    defaultCallOptions: CallOptions = CallOptions(),
    interceptors: VideoCall_VideoCallClientInterceptorFactoryProtocol? = nil
  ) {
    self.channel = channel
    self.defaultCallOptions = defaultCallOptions
    self.interceptors = interceptors
  }
}

/// To build a server, implement a class that conforms to this protocol.
internal protocol VideoCall_VideoCallProvider: CallHandlerProvider {
  var interceptors: VideoCall_VideoCallServerInterceptorFactoryProtocol? { get }

  func video_call(request: VideoCall_VideoCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_ServerResponse>

  func cancel_request_call(request: VideoCall_VideoCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_BaseResponse>

  func miss_call(request: VideoCall_VideoCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_BaseResponse>

  func decline_call(request: VideoCall_VideoCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_BaseResponse>

  func end_call(request: VideoCall_VideoCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_BaseResponse>

  func update_call(request: VideoCall_UpdateCallRequest, context: StatusOnlyCallContext) -> EventLoopFuture<VideoCall_BaseResponse>
}

extension VideoCall_VideoCallProvider {
  internal var serviceName: Substring { return "video_call.VideoCall" }

  /// Determines, calls and returns the appropriate request handler, depending on the request's method.
  /// Returns nil for methods not handled by this service.
  internal func handle(
    method name: Substring,
    context: CallHandlerContext
  ) -> GRPCServerHandlerProtocol? {
    switch name {
    case "video_call":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<VideoCall_VideoCallRequest>(),
        responseSerializer: ProtobufSerializer<VideoCall_ServerResponse>(),
        interceptors: self.interceptors?.makevideo_callInterceptors() ?? [],
        userFunction: self.video_call(request:context:)
      )

    case "cancel_request_call":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<VideoCall_VideoCallRequest>(),
        responseSerializer: ProtobufSerializer<VideoCall_BaseResponse>(),
        interceptors: self.interceptors?.makecancel_request_callInterceptors() ?? [],
        userFunction: self.cancel_request_call(request:context:)
      )

    case "miss_call":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<VideoCall_VideoCallRequest>(),
        responseSerializer: ProtobufSerializer<VideoCall_BaseResponse>(),
        interceptors: self.interceptors?.makemiss_callInterceptors() ?? [],
        userFunction: self.miss_call(request:context:)
      )

    case "decline_call":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<VideoCall_VideoCallRequest>(),
        responseSerializer: ProtobufSerializer<VideoCall_BaseResponse>(),
        interceptors: self.interceptors?.makedecline_callInterceptors() ?? [],
        userFunction: self.decline_call(request:context:)
      )

    case "end_call":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<VideoCall_VideoCallRequest>(),
        responseSerializer: ProtobufSerializer<VideoCall_BaseResponse>(),
        interceptors: self.interceptors?.makeend_callInterceptors() ?? [],
        userFunction: self.end_call(request:context:)
      )

    case "update_call":
      return UnaryServerHandler(
        context: context,
        requestDeserializer: ProtobufDeserializer<VideoCall_UpdateCallRequest>(),
        responseSerializer: ProtobufSerializer<VideoCall_BaseResponse>(),
        interceptors: self.interceptors?.makeupdate_callInterceptors() ?? [],
        userFunction: self.update_call(request:context:)
      )

    default:
      return nil
    }
  }
}

internal protocol VideoCall_VideoCallServerInterceptorFactoryProtocol {

  /// - Returns: Interceptors to use when handling 'video_call'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makevideo_callInterceptors() -> [ServerInterceptor<VideoCall_VideoCallRequest, VideoCall_ServerResponse>]

  /// - Returns: Interceptors to use when handling 'cancel_request_call'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makecancel_request_callInterceptors() -> [ServerInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'miss_call'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makemiss_callInterceptors() -> [ServerInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'decline_call'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makedecline_callInterceptors() -> [ServerInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'end_call'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeend_callInterceptors() -> [ServerInterceptor<VideoCall_VideoCallRequest, VideoCall_BaseResponse>]

  /// - Returns: Interceptors to use when handling 'update_call'.
  ///   Defaults to calling `self.makeInterceptors()`.
  func makeupdate_callInterceptors() -> [ServerInterceptor<VideoCall_UpdateCallRequest, VideoCall_BaseResponse>]
}
