# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

use_modular_headers!

def shared_pods
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SignalProtocolObjC', :git =>'https://github.com/nohtbook/SignalProtocol-ObjC.git'
  # Waiting on merge https://github.com/yapstudios/YapDatabase/pull/492
  pod 'YapDatabase/SQLCipher', '~> 4.0'
  pod 'Mantle', '~> 2.1.6'
  pod 'RealmSwift'
  pod 'SocketRocket'
  pod 'GoogleWebRTC'
  pod 'GoogleSignIn'
  
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'MSAL'
  
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'Introspect'
end

target 'ClearKeep' do
  shared_pods
end

target 'ClearKeep Development' do
  shared_pods
end

target 'ClearKeep Staging' do
  shared_pods
end

target 'NotificationServiceExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SignalProtocolObjC', :git =>'https://github.com/nohtbook/SignalProtocol-ObjC.git'
  pod 'YapDatabase/SQLCipher', '~> 4.0'
  pod 'Mantle', '~> 2.1.6'
  pod 'RealmSwift'
end
